flyway.url=jdbc:postgresql://localhost:5432/assistive_ai
flyway.user=postgres
flyway.password=root123
flyway.schemas=public
flyway.locations=filesystem:sql
flyway.baselineOnMigrate=false
flyway.cleanDisabled=false